from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import subprocess
from typing import Dict, List

try:
    from .experiment_config import BaselineConfig
except ImportError:
    from experiment_config import BaselineConfig


@dataclass
class BaselineRunSpec:
    name: str
    source_url: str
    local_dir: Path
    notes: str


def list_baseline_specs(root: str = "external") -> List[BaselineRunSpec]:
    cfg = BaselineConfig(root=root)
    notes: Dict[str, str] = {
        "patchtst": (
            "Clone the official PatchTST repo here and adapt its long-term "
            "forecasting script to the processed CSV/NPZ generated by this project."
        ),
        "itransformer": (
            "Clone THUML iTransformer. Use its standard ETT/ECL/Weather protocol "
            "for general datasets and battery processed cycle tables for SOH baselines."
        ),
        "timecma": (
            "Clone TimeCMA for prompt-assisted baseline comparisons. Keep dataset "
            "splits identical to GraphReportTS when comparing battery SOH."
        ),
        "timesnet": "Use THUML Time-Series-Library implementation for TimesNet baseline.",
        "dlinear": "Use LTSF-Linear for DLinear/NLinear lightweight baselines.",
        "time_llm": "Use Time-LLM official implementation if GPU/API budget allows.",
    }
    return [
        BaselineRunSpec(
            name=name,
            source_url=url,
            local_dir=Path(root) / name,
            notes=notes.get(name, "Add a thin adapter around the official training entry point."),
        )
        for name, url in cfg.sources.items()
    ]


def print_baseline_setup(root: str = "external") -> None:
    print("External baseline source code is not vendored. Suggested setup:")
    for spec in list_baseline_specs(root):
        print(f"- {spec.name}: {spec.source_url}")
        print(f"  local_dir: {spec.local_dir}")
        print(f"  notes: {spec.notes}")


def clone_baselines(root: str = "external", names: List[str] | None = None, dry_run: bool = True) -> None:
    specs = list_baseline_specs(root)
    selected = set(names or [s.name for s in specs])
    Path(root).mkdir(parents=True, exist_ok=True)
    for spec in specs:
        if spec.name not in selected:
            continue
        cmd = ["git", "clone", spec.source_url, str(spec.local_dir)]
        if spec.local_dir.exists():
            print(f"skip existing {spec.local_dir}")
            continue
        print(" ".join(cmd))
        if not dry_run:
            subprocess.run(cmd, check=True)


def parse_args():
    p = argparse.ArgumentParser(description="Prepare official baseline repositories")
    p.add_argument("--root", type=str, default="external")
    p.add_argument("--clone", action="store_true", help="Actually clone selected baseline repositories")
    p.add_argument("--names", type=str, default="", help="Comma-separated baseline names; default all")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    print_baseline_setup(args.root)
    names = [x.strip() for x in args.names.split(",") if x.strip()] or None
    clone_baselines(args.root, names=names, dry_run=not args.clone)
